//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetHistory
    {
        public int id { get; set; }
        public int lot_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public int coast { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Lot Lot { get; set; }
        public virtual User User { get; set; }
    }
}
