//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotProperty
    {
        public int id { get; set; }
        public int lot_id { get; set; }
        public string property { get; set; }
        public string description { get; set; }
    
        public virtual Lot Lot { get; set; }
    }
}
