//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepBet
    {
        public int Id { get; set; }
        public int Lot_Id { get; set; }
        public int User_Id { get; set; }
        public decimal MaxBet { get; set; }
        public decimal Step { get; set; }
    
        public virtual Lot Lot { get; set; }
        public virtual User User { get; set; }
    }
}
