//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BetHistories = new HashSet<BetHistory>();
            this.Lots = new HashSet<Lot>();
            this.Lots1 = new HashSet<Lot>();
            this.UserInRoles = new HashSet<UserInRole>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public int money { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<BetHistory> BetHistories { get; set; }
        public virtual ICollection<Lot> Lots { get; set; }
        public virtual ICollection<Lot> Lots1 { get; set; }
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
    }
}
